imports:
    - { resource: admin.yml }

    # Vendors

    - { resource: vendor/blast/base_entities.yml }
    - { resource: vendor/blast/csv_import.yml }
    - { resource: vendor/blast/dashboard.yml }
    - { resource: vendor/blast/menu.yml }
    - { resource: vendor/blast/resource.yml }
    - { resource: vendor/blast/search.yml }
    - { resource: vendor/blast/utils.yml }

    - { resource: vendor/stof.yml }
    - { resource: vendor/sil.yml }
    - { resource: vendor/sonata.yml }
    - { resource: vendor/sylius.yml }
    - { resource: vendor/lexik.yml }
    - { resource: vendor/fos.yml }
    - { resource: vendor/doctrine.yml }
    - { resource: vendor/stfalcon.yml }

    # SIL Bundles

    - { resource: "@SilSonataSyliusUserBundle/Resources/config/parameters.yml" }
    - { resource: "@SilSonataSyliusUserBundle/Resources/config/app/config.yml" }

    - { resource: "@SilEmailBundle/Resources/config/parameters.yml" }
    - { resource: "@SilEmailBundle/Resources/config/app/config.yml" }

    - { resource: "@SilEcommerceBundle/Resources/config/parameters.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/app/config.yml" }

    - { resource: "@SilCRMBundle/Resources/config/parameters.yml" }
    - { resource: "@SilCRMBundle/Resources/config/app/config.yml" }

    - { resource: "@SilMediaBundle/Resources/config/parameters.yml" }
    - { resource: "@SilMediaBundle/Resources/config/app/config.yml" }

    - { resource: "@SilSyliusPayboxBundle/Resources/config/parameters.yml" }
    - { resource: "@SilSyliusPayboxBundle/Resources/config/app/config.yml" }

    - { resource: "@SilUomBundle/Resources/config/app/config.yml" }

    - { resource: "@SilStockBundle/Resources/config/parameters.yml" }
    - { resource: "@SilStockBundle/Resources/config/app/config.yml" }
    - { resource: "@SilStockBundle/Resources/config/services.yml" }

    - { resource: "@SilManufacturingBundle/Resources/config/parameters.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/app/config.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/services.yml" }

    - { resource: admin.yml }

    # Vendors
    - { resource: vendor/blast/base_entities.yml }
    - { resource: vendor/blast/menu.yml }
    - { resource: vendor/blast/resource.yml }
    - { resource: vendor/blast/utils.yml }
