parameters:
    sil_crm.entity.address.class:                       PlatformBundle\Entity\SilCRMBundle\Address
    sil_crm.entity.organism.class:                      PlatformBundle\Entity\SilCRMBundle\Organism

    sil_stock.entity.partner.class:                     "%sil_crm.entity.organism.class%"
    sil_stock.entity.stock_item.class:                  "%sil_ecommerce.entity.product.class%"

    sil_ecommerce.entity.product.class:                 LisemBundle\Entity\SilEcommerceBundle\Product
    sil_ecommerce.entity.order.class:                   LisemBundle\Entity\SilEcommerceBundle\Order
    sil_ecommerce.entity.product_variant.class:         LisemBundle\Entity\SilEcommerceBundle\ProductVariant
    sil_ecommerce.entity.product_option_value.class:    LisemBundle\Entity\SilEcommerceBundle\ProductOptionValue

    sil_media.entity.file.class:                        PlatformBundle\Entity\SilMediaBundle\File

    sil_email.entity.email.class:                       PlatformBundle\Entity\SilEmailBundle\Email

    sil_sonata_sylius_user.entity.sonata_user.class:    PlatformBundle\Entity\SilSonataSyliusUserBundle\SonataUser
    sil_sonata_sylius_user.entity.sonata_group.class:   Sil\Bundle\SonataSyliusUserBundle\Entity\SonataGroup

    sil_variety.entity.family.class:                    PlatformBundle\Entity\SilVarietyBundle\Family
    sil_variety.entity.variety.class:                   PlatformBundle\Entity\SilVarietyBundle\Variety
    sil_variety.entity.species.class:                   PlatformBundle\Entity\SilVarietyBundle\Species
    sil_variety.entity.genus.class:                     PlatformBundle\Entity\SilVarietyBundle\Genus

    sil_seed_batch.entity.seed_batch.class:             Sil\Bundle\SeedBatchBundle\Entity\SeedBatch

    sil_platform.entity.channel_description.class:      PlatformBundle\Entity\ChannelDescription
