language: php

php:
  - '7.1'
  - nightly


services:
  - postgresql
  - elasticsearch

sudo: required

cache:
  pip: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.nvm/.cache/
    - node_modules
    
env:
  global:
    - PATH="$HOME/.local/bin:$PATH"
    - SCRIPTS_FOLDER=bin/ci-scripts
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - TARGET=test
    - XMLLINT_INDENT="    "

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: TARGET=docs
    - php: '7.1'
      env: TARGET=lint
    - php: '7.1'
      env: TARGET=ant
  allow_failures:
    - php: nightly
    - env: SYMFONY_DEPRECATIONS_HELPER=0

before_install:
    - ln -s .env.travis .env # Enable env
    - if [[ -x ${SCRIPTS_FOLDER}/check_relevant_${TARGET}.sh && "$TRAVIS_PULL_REQUEST" != "false" ]]; then export RELEVANT=$(${SCRIPTS_FOLDER}/check_relevant_${TARGET}.sh); fi;
    - if [[ ! -z ${RELEVANT} ]];then exit 0; fi;
    - if [ -x ${SCRIPTS_FOLDER}/before_install_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/before_install_${TARGET}.sh; fi;
    - if [ -x ${SCRIPTS_FOLDER}/create_database_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/create_database_${TARGET}.sh; fi;

install:
    - if [ -x ${SCRIPTS_FOLDER}/install_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/install_${TARGET}.sh; fi;

before_script:
    - if [ -x ${SCRIPTS_FOLDER}/before_script_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/before_script_${TARGET}.sh; fi;

script:
    - if [ -x ${SCRIPTS_FOLDER}/run_${TARGET}.sh ]; then travis_wait 42 ${SCRIPTS_FOLDER}/run_${TARGET}.sh; fi;

after_success:
    - if [ -x ${SCRIPTS_FOLDER}/after_success_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/after_success_${TARGET}.sh; fi;

after_failure:
    - if [ -x ${SCRIPTS_FOLDER}/after_failure_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/after_failure_${TARGET}.sh; fi;
