csv_mapping:

    Sil\Bundle\VarietiesBundle\Entity\Family:
        filename: famille.csv
        fields:
            'nom':         name
            'alias':       alias
            'nom latin':   latin_name
            'description': description

    Sil\Bundle\VarietiesBundle\Entity\Genus:
        filename: genre.csv
        fields:
            'nom':         name
            'alias':       alias
            'nom latin':   latin_name
            'description': description
            'famille':     family

    Sil\Bundle\VarietiesBundle\Entity\Species:
        filename: espece.csv
        fields:
            'nom':                    name
            'alias':                  alias
            'nom latin':              latin_name
            'description':            description
            'genre':                  genus
            'sous-espèce de':         parent_species
            'taux germination légal': legal_germination_rate
            'PMG':                    tkw
            'durée de levée':         raise_duration
            'cycle végétatif':        life_cycle
            'statut réglementaire':   regulatory_status
            'taux germination':       legal_germination_rate
            'durée vie':              seed_lifespan
            'taux germination AS':    germination_rate

    Sil\Bundle\VarietiesBundle\Entity\Variety:
        filename: variete.csv
        fields:
            'nom':                    name
            'code':                   code
            'alias':                  alias
            'nom latin':              latin_name
            'description':            description
            'espèce':                 species
            'taux germination légal': legal_germination_rate
            'taux germination AS':    germination_rate
            'PMG':                    tkw
            'durée vie':              seed_lifespan
            'durée de levée':         raise_duration
            'maladies transmises':    transmitted_diseases
            'cycle végétatif':        life_cycle
            'statut réglementaire':   regulatory_status
            'inscrit CO':             official
            'nom CO':                 official_name
            'date inscription CO':    official_date_in
            'date radiation CO':      official_date_out
            'mainteneur':             official_maintainer
