imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

    # Vendors

    - { resource: vendors/blast.yml }
    - { resource: vendors/sil.yml }
    - { resource: vendors/sonata.yml }
    - { resource: vendors/sylius.yml }
    - { resource: vendors/lexik.yml }
    - { resource: vendors/fos.yml }
    - { resource: vendors/doctrine.yml }

    # BLAST Bundles

    - { resource: "@BlastCoreBundle/Resources/config/config.yml" }
    # - { resource: "@BlastBaseEntitiesBundle/Resources/config/app/config.yml" }# overriden in app/config/vendors/blast.yml
    # - { resource: "@BlastResourceBundle/Resources/config/app/config.yml" }    # overriden in app/config/vendors/blast.yml
    - { resource: "@BlastUtilsBundle/Resources/config/app/config.yml" }

    # SIL Bundles

    - { resource: "@SilSonataSyliusUserBundle/Resources/config/parameters.yml" }
    - { resource: "@SilSonataSyliusUserBundle/Resources/config/app/config.yml" }

    - { resource: "@SilEmailBundle/Resources/config/parameters.yml" }

    - { resource: "@SilSeedBatchBundle/Resources/config/parameters.yml" }
    - { resource: "@SilSeedBatchBundle/Resources/config/app/config.yml" }

    - { resource: "@SilEcommerceBundle/Resources/config/parameters.yml" }
    # - { resource: "@SilEcommerceBundle/Resources/config/app/config.yml" }     # overriden in LisemBundle

    - { resource: "@SilCRMBundle/Resources/config/parameters.yml" }
    - { resource: "@SilCRMBundle/Resources/config/app/config.yml" }

    - { resource: "@SilMediaBundle/Resources/config/parameters.yml" }
    - { resource: "@SilMediaBundle/Resources/config/app/config.yml" }

    - { resource: "@SilSyliusPayboxBundle/Resources/config/parameters.yml" }
    - { resource: "@SilSyliusPayboxBundle/Resources/config/app/config.yml" }

    - { resource: "@SilStockBundle/Resources/config/parameters.yml" }
    - { resource: "@SilStockBundle/Resources/config/app/config.yml" }
    - { resource: "@SilStockBundle/Resources/config/services.yml" }

    - { resource: "@SilManufacturingBundle/Resources/config/parameters.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/app/config.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/services.yml" }

    - { resource: "@SilVarietyBundle/Resources/config/parameters.yml" }

    # Platform Bundle

    - { resource: "@PlatformBundle/Resources/config/parameters.yml" }
    - { resource: "@PlatformBundle/Resources/config/config.yml" }

    # Li LISEM

    - { resource: "@LisemBundle/Resources/config/parameters.yml" }
    - { resource: "@LisemBundle/Resources/config/config.yml" }
    - { resource: "@LisemBundle/Resources/config/varieties.yml" }
    - { resource: "@LisemBundle/Resources/config/sonata.yml" }
    - { resource: "@LisemBundle/Resources/config/services.yml" }
    - { resource: "@LisemBundle/Resources/config/sylius-fixtures.yml" }
    - { resource: "@LisemBundle/Resources/config/grids.yml" }
    - { resource: "@LisemBundle/Resources/config/state_machine.yml" }
    - { resource: "@LisemBundle/Resources/config/admin.yml" }

parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: blast_doctrine_handler
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SonataCoreBundle:Form:colorpicker.html.twig'
        - 'BlastCoreBundle:Admin/Form:fields.html.twig'
        - 'BlastUtilsBundle:Form:fields.html.twig'
        - 'BlastBaseEntitiesBundle:Form:fields.html.twig'
        - 'SilMediaBundle:Form:fields.html.twig'
    globals:
        sil:
            url_prefix: "%sil.url_prefix%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            session:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                naming_strategy: blast.resource.doctrine.orm.naming_strategy.underscored_bundle_prefix
                # naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:

                    # Blast

                    BlastBaseEntitiesBundle:
                        type: yml

                    # Sil

                    SilCRMBundle:
                        type: yml
                    SilEcommerceBundle:
                        type: yml
                    SilEmailBundle:
                        type: yml
                    SilEmailCRMBundle:
                        type: yml
                    SilManufacturingBundle:
                        type: yml
                        prefix: Sil\Bundle\ManufacturingBundle\Domain\Entity
                    SilMediaBundle:
                        type: yml
                    SilSeedBatchBundle:
                        type: yml
                    SilSonataSyliusUserBundle:
                        type: yml
                    SilStockBundle:
                        type: yml
                        prefix: Sil\Bundle\StockBundle\Domain\Entity
                    SilVarietyBundle:
                        type: yml

                    # Platform

                    PlatformBundle:
                        type: yml

                    # Project

                    LisemBundle:
                        type: yml

                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                dql:
                    string_functions:
                        ilike: Blast\DoctrinePgsqlBundle\DoctrineExtensions\Functions\Ilike
                        concat_ws: Oro\ORM\Query\AST\Functions\String\ConcatWs
            session:
                connection: session
                naming_strategy: blast.resource.doctrine.orm.naming_strategy.underscored_bundle_prefix
                # naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false # Only one entity manager can have auto_mappping set to true
                mappings:
                    BlastDoctrineSessionBundle:
                        type: yml

# Swiftmailer Configuration
swiftmailer:
    default_mailer: direct_mailer
    mailers:
        direct_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            delivery_addresses: ['jardinenvie@lisem.eu']
            disable_delivery:  "%mailer_disable_delivery%"
        spool_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool: { type: db }
            delivery_addresses: ['jardinenvie@lisem.eu']
            disable_delivery:  "%mailer_disable_delivery%"
