sylius:
    resource: "routing/sylius.yml"

liip:
    resource: "routing/liip.yml"

blast:
    resource: "routing/blast.yml"

sonata:
    resource: "routing/sonata.yml"

lisem:
    resource: "@LisemBundle/Resources/config/routing.yml"
