
services:
    lisem.admin.seeds_product:
        class: LisemBundle\Admin\SeedsProductAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Product, LisemBundle:SeedsProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.lisembundle.admin.seeds_product
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductAdmin:edit.html.twig ] ]

