
services:
    lisem.admin.seeds_product_variant:
        class: LisemBundle\Admin\SeedsProductVariantAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ProductVariant, SilEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.lisembundle.seeds_product_variant
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

