
services:
    lisem.admin.channel_description:
        class: LisemBundle\Admin\ChannelDescriptionAdmin
        arguments: [~, PlatformBundle\Entity\ChannelDescription, BlastCoreBundle:CRUD ]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.lisembundle.admin.channel_description
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
