
services:
    lisem.admin.other_product:
        class: LisemBundle\Admin\OtherProductAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Product, SilEcommerceBundle:ProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.lisembundle.admin.other_product
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductAdmin:edit.html.twig ] ]

