
services:
    sil_ecommerce.admin.payment_method:
        class: LisemBundle\Admin\PaymentMethodAdmin
        arguments: [~, Sylius\Component\Core\Model\PaymentMethod, SilEcommerceBundle:PaymentCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.payment_method
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
