imports:

    # SilCRMBundle
    #
    # - { resource: "@SilCRMBundle/Resources/config/admin.yml" }

    # SilEcommerceBundle
    #
    # - { resource: "@SilEcommerceBundle/Resources/config/admin.yml" }
