imports:

    # SilCRMBundle
    #
    # - { resource: "@SilCRMBundle/Resources/config/admin.yml" }

    # SilEcommerceBundle
    #
    # - { resource: "@SilEcommerceBundle/Resources/config/admin.yml" }

    # SilEmailBundle
    #
    # - { resource: "@SilEmailBundle/Resources/config/admin.yml" }

    # SilEmailCRMBundle
    #
    # - { resource: "@SilEmailCRMBundle/Resources/config/admin.yml" }

    # SilManufacturingBundle
    #
    # - { resource: "@SilManufacturingBundle/Resources/config/admin.yml" }

    # SilSeedBatchBundle
    #
    # - { resource: "@SilSeedBatchBundle/Resources/config/admin.yml" }

    # SilSonataSyliusUserBundle
    #
    # - { resource: "@SilSonataSyliusUserBundle/Resources/config/admin.yml" }
