parameters:

    blast_menu.settings:

        sil.ecommerce.menu_label.shop_settings:
            icon: cart-plus
            order: 20000
            children:

                sil.ecommerce.menu_label.shop_settings_channels:
                    icon: random
                    route: admin_sil_ecommerce_channel_list
                    order: 20010

                sil.ecommerce.menu_label.shop_settings_taxons:
                    icon: list
                    route: admin_sil_ecommerce_taxon_list
                    order: 20020

                sil.ecommerce.menu_label.shop_settings_product_attributes:
                    icon: tag
                    route: admin_sil_ecommerce_productattribute_list
                    order: 20030

                sil.ecommerce.menu_label.shop_settings_product_options:
                    icon: sliders
                    route: admin_sil_ecommerce_productoption_list
                    order: 20040

                sil.ecommerce.menu_label.shop_settings_zones:
                    icon: globe
                    route: admin_sil_ecommerce_zone_list
                    order: 20050

                sil.ecommerce.menu_label.shop_settings_payment_methods:
                    icon: credit-card
                    route: admin_sil_ecommerce_payment_method_list
                    order: 20060

                sil.ecommerce.menu_label.shop_settings_shipping_methods:
                    icon: truck
                    route: admin_sil_ecommerce_shipping_method_list
                    order: 20070

                sil.ecommerce.menu_label.shop_settings_tax_categories:
                    icon: gavel
                    route: admin_sil_ecommerce_taxcategory_list
                    order: 20080

                sil.ecommerce.menu_label.shop_settings_tax_rates:
                    icon: percent
                    route: admin_sil_ecommerce_taxrate_list
                    order: 20090

                sil.ecommerce.menu_label.shop_settings_shop_users:
                    icon: user-circle-o
                    route: admin_sil_ecommerce_shop_user_list
                    order: 20100
