PlatformBundle\Entity\SilEcommerceBundle\Product:
    type: mappedSuperclass
    table: sil_ecommerce_product

    manyToOne:
        uom:
            targetEntity: Sil\Bundle\UomBundle\Entity\Uom
            joinColumn:
                name: uom_id
                referencedColumnName: id
                nullable: false
        outputStrategy:
            targetEntity: Sil\Bundle\StockBundle\Domain\Entity\OutputStrategy
            joinColumn:
                name: strategy_output_id
                referencedColumnName: id
                nullable: false
