PlatformBundle\Entity\SilMediaBundle\File:
    type: entity
    fields:
        path:
            type: string
            nullable: true
            unique: true
        type:
            type: string
            nullable: true
            unique: false
    manyToOne:
        owner:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductInterface
            inversedBy: images
