PlatformBundle\Entity\SilVarietyBundle\Variety:
    type: entity

    oneToMany:
        products:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductInterface
            mappedBy: variety
        channelDescriptions:
            targetEntity: PlatformBundle\Entity\ChannelDescription
            mappedBy: variety
            cascade: [ persist, remove ]
            orphanRemoval: true
        seedBatches:
            targetEntity: Sil\Bundle\SeedBatchBundle\Entity\SeedBatch
            mappedBy: variety

    manyToMany:
        packagings:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductOptionValueInterface
            cascade: [ persist, remove ]

        plant_categories:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\PlantCategory
            joinTable:
                name: platformy_variety__plant_category
                joinColumns:
                    plantCategory_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    variety_id:
                        referencedColumnName: id
