parameters:
    blast_menu.root:

        sil.crm.menu_label.organism:
            icon: address-card
            route: admin_sil_crm_organism_list
            order: 10100

    blast_menu.settings:

        sil.crm.menu_label.crm_settings:
            icon: address-card
            order: 10100
            children:

                sil.crm.menu_label.crm_settings_circles:
                    icon: circle-o-notch
                    route: admin_sil_crm_circle_list
                    order: 10110

                sil.crm.menu_label.crm_settings_categories:
                    icon: tags
                    route: admin_sil_crm_category_list
                    order: 10120

                sil.crm.menu_label.crm_settings_position_types:
                    icon: id-badge
                    route: admin_sil_crm_positiontype_list
                    order: 10130

                sil.crm.menu_label.crm_settings_phone_types:
                    icon: phone-square
                    route: admin_sil_crm_phonetype_list
                    order: 10140
